server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Necesario para React Router — todo redirige al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Evitar exponer info del servidor
    server_tokens off;
}